# Generated by Django 4.2.3 on 2023-07-12 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrullancapp', '0002_personal_estado_civil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='bono_colacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='bono_movilizacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='cargo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrullancapp.comuna'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='estado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='sueldo_base',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
