# Generated by Django 4.2.3 on 2023-07-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrullancapp', '0003_alter_personal_bono_colacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoring',
            name='estado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factoring',
            name='n_factura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factoring',
            name='nombre_factoring',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factoring',
            name='rut_factoring',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='kilometraje',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factoring',
            name='fecha_factoring',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factoring',
            name='monto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='serie_chasis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='serie_motor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
