# Generated by Django 4.2.3 on 2023-07-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrullancapp', '0004_factoring_estado_factoring_n_factura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialesporproyecto',
            name='material',
        ),
        migrations.RemoveField(
            model_name='subcontratistasporproyectos',
            name='subcontratista',
        ),
        migrations.AddField(
            model_name='materialesporproyecto',
            name='material',
            field=models.ManyToManyField(to='carrullancapp.materiales'),
        ),
        migrations.AddField(
            model_name='subcontratistasporproyectos',
            name='subcontratista',
            field=models.ManyToManyField(to='carrullancapp.subcontratistas'),
        ),
    ]
