# Generated by Django 4.2.3 on 2023-07-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrullancapp', '0005_remove_materialesporproyecto_material_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProyectoMAVEServiu',
            new_name='SubProyectoMAVEServiu',
        ),
        migrations.AddField(
            model_name='proyectos',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='fecha_modificacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
