# Generated by Django 4.2.3 on 2023-07-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrullancapp', '0006_rename_proyectomaveserviu_subproyectomaveserviu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculos',
            old_name='año',
            new_name='anio',
        ),
    ]
