# Generated by Django 4.2.3 on 2023-07-24 15:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carrullancapp', '0007_rename_año_vehiculos_anio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analisispreciosunitarios',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='analisispreciosunitarios',
            name='material',
        ),
        migrations.RemoveField(
            model_name='analisispreciosunitarios',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='analisispreciosunitarios',
            name='total',
        ),
        migrations.AddField(
            model_name='analisispreciosunitarios',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analisispreciosunitarios',
            name='nombre',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MaterialCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_costs', to='carrullancapp.analisispreciosunitarios')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrullancapp.materiales')),
            ],
        ),
        migrations.CreateModel(
            name='LaborCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('rendimiento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_costs', to='carrullancapp.analisispreciosunitarios')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('rendimiento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_costs', to='carrullancapp.analisispreciosunitarios')),
            ],
        ),
    ]
